[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Force deployment - Updated to include latest loading screen improvements
# Deployment timestamp: 2024-06-01 - Loading screen with 0.5s delay, webpack fixes 